project_id = "est-fe-13-3rd-project"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[functions.generate-custom-recipe]
verify_jwt = true

[functions.answer-recipe-question]
verify_jwt = true
